<div class="container">
    <div class="row">
        <div class="col-md-12">
            <form class="navbar-form" role="search" action="/result">
            <div class="input-group">
                <input type="text" name="search" class="form-control" placeholder="Zoeken naar ..."/>
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search"></span></button>
                </span>
            </div>
            </form>
        </div>
    </div>
</div>