<!--Author Isaac de Cuba-->
<!--Editor Adriel Walter, Serhildan Akdeniz, Karam Jezrawi-->
<?php echo $this->doctype() ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <?php echo $this->headTitle(); ?>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headScript(); ?>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->serverUrl(); ?>">Funda</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="<?php echo $this->serverUrl(); ?>">Home</a></li>
            </ul>
        </div>
    </div>
</nav>
<a id="filter" class="sidebar" href="#sidr" xmlns="http://www.w3.org/1999/html"><p class="vertical-text lead">
        FILTERS</p></a>
<div id="sidr">
    <nav class="menu slide-menu-left">
        <form method="get" action="#">
            <div class="row">
                <p>Aanwezigheid van</p>
                <div class="col-lg-6">
                    <div class="clearfix"></div>
                    <label>
                        <input name="balkon" type="checkbox"> Balkon<br>
                    </label>
                    <label>
                        <input name="lift" type="checkbox"> Lift<br>
                    </label>
                    <label>
                        <input name="garage" type="checkbox"> Garage<br>
                    </label>
                    <label>
                        <input name="tuin" type="checkbox"> Tuin<br>
                    </label>
                    <label>
                        <input name="zwembad" type="checkbox"> Zwembad<br>
                    </label>
                </div><!-- /.col-lg-6 -->
            </div><!-- /.row -->
            <hr/>
            <div class="row">
                <p>Aantal kamers</p>
                <div class="col-lg-6">
                    <label>
                        <input name="kamers" type="radio"> 1 kamer<br>
                    </label>
                    <label>
                        <input name="kamers" type="radio"> 2+ kamers<br>
                    </label>
                    <label>
                        <input name="kamers" type="radio" > 3+ kamers<br>
                    </label>
                    <label>
                        <input name="kamers" type="radio"> 4+ kamers<br>
                    </label>
                </div><!-- /.col-lg-6 -->
            </div><!-- /.row -->
            <hr/>
            <!-- hier gestopt -->
            <p>Woonoppervlakte</p>
            <select class="form-control">
                <option name="wgeenvoorkeur" class="filter_option_no">Geen voorkeur</option>
                <option name="50m" class="filter_option">50+ m</option>
                <option name="75m" class="filter_option">75+ m</option>
                <option name="100m" class="filter_option">100+ m</option>
                <option name="150m" class="filter_option">150+ m</option>
            </select>
            <hr/>
            <p>Energielabel</p>
            <select class="form-control">
                <option name="lgeenvoorkeur" class="filter_option_no">Geen voorkeur</option>
                <option name="a-label" class="filter_option">A-label</option>
                <option name="b-label" class="filter_option">B-label</option>
                <option name="c-label" class="filter_option">C-label</option>
                <option name="d-label" class="filter_option">D-label</option>
                <option name="e-label" class="filter_option">E-label</option>
                <option name="f-label" class="filter_option">F-label</option>
                <option name="g-label" class="filter_option">G-label</option>
            </select>
            <hr/>
            <p>Prijsklasse</p>
            <select  class="form-control"  id="sale_amount" name="sale_amount">
                <option selected="selected" value="0">€ 0</option>
                <option value="0-50000">€ 0 - 50.000</option>
                <option value="0-75000">€ 0 - € 75.000</option>
                <option value="0-100000">€ 0 - € 100.000</option>
                <option value="0-125000">€ 0 - € 125.000</option>
                <option value="0-150000">€ 0 - € 150.000</option>
                <option value="0-175000">€ 0 - € 175.000</option>
                <option value="0-200000">€ 0 - € 200.000</option>
                <option value="0-225000">€ 0 - € 225.000</option>
                <option value="0-250000">€ 0 - € 250.000</option>
                <option value="0-275000">€ 0 - € 275.000</option>
                <option value="0-300000">€ 0 - € 300.000</option>
                <option value="0-325000">€ 0 - € 325.000</option>
                <option value="0-350000">€ 0 - € 350.000</option>
                <option value="0-375000">€ 0 - € 375.000</option>
                <option value="0-400000">€ 0 - € 400.000</option>
                <option value="0-450000">€ 0 - € 450.000</option>
                <option value="0-500000">€ 0 - € 500.000</option>
                <option value="0-550000">€ 0 - € 550.000</option>
                <option value="0-600000">€ 0 - € 600.000</option>
                <option value="0-650000">€ 0 - € 650.000</option>
                <option value="0-700000">€ 0 - € 700.000</option>
                <option value="0-750000">€ 0 - € 750.000</option>
                <option value="0-800000">€ 0 - € 800.000</option>
                <option value="0-900000">€ 0 - € 900.000</option>
                <option value="0-1000000">€ 0 - € 1.000.000</option>
                <option value="0-1250000">€ 0 - € 1.250.000</option>
                <option value="0-1500000">€ 0 - € 1.500.000</option>
                <option value="0-2000000">€ 0 - € 2.000.000</option>
            </select>
        </form>
    </nav>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="page-header">
            </div>
        </div>
    </div>
    <?php echo $this->layout()->content ?><br />

    <div class="row" id="final-footer">
        <div class="col-md-12 text-center">
            <span class="glyphicon glyphicon-copyright-mark"/> 2000-2015 Funda Real Estate B.V.
        </div>
    </div>
</div>
</body>
</html>

