<!--Author Isaac de Cuba-->
<!--Editor Adriel Walter, Serhildan Akdeniz-->
<?php echo $this->doctype() ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <?php echo $this->headTitle(); ?>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headScript(); ?>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->serverUrl(); ?>">Funda</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="<?php echo $this->serverUrl(); ?>">Home</a></li>
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="page-header">
            </div>
        </div>
    </div>
</div>
<a id="filter" class="sidebar" href="#sidr" xmlns="http://www.w3.org/1999/html"><p class="vertical-text lead">
        FILTERS</p></a>
<div id="sidr">
    <form action="/result">
        <div class="container-fluid">
            <nav class="menu slide-menu-left">
                <div class="row">
                    <p>Aanwezigheid van</p>
                    <div class="col-md-12">
                        <label><input name="balkon" type="checkbox"> Balkon</label><br />
                        <label><input name="lift" type="checkbox"> Lift</label><br />
                        <label><input name="garage" type="checkbox"> Garage</label><br />
                        <label><input name="tuin" type="checkbox"> Tuin</label><br />
                        <label><input name="zwembad" type="checkbox"> Zwembad</label><br />
                    </div> <!-- .col-md-6 -->
                </div> <!-- .row -->
                <hr/>
                <div class="row">
                    <p>Aantal kamers</p>
                    <div class="col-md-6">
                        <label><input name="kamers" type="radio"> 1 kamer</label><br />
                        <label><input name="kamers" type="radio"> 2+ kamers</label><br />
                        <label><input name="kamers" type="radio" > 3+ kamers</label><br />
                        <label><input name="kamers" type="radio"> 4+ kamers<br></label><br />
                    </div> <!-- .col-md-6 -->
                </div> <!-- .row -->
                <hr/>
                <div class="row">
                    <div class="col-md-12">
                        <p>Woonoppervlakte</p>
                        <select id="woonoppervlakte" name="woonoppervlakte">
                            <option value="default" disabled="disabled" selected="selected">Selecteer</option>
                            <option value="50m" class="filter_option">50+ m</option>
                            <option value="75m" class="filter_option">75+ m</option>
                            <option value="100m" class="filter_option">100+ m</option>
                            <option value="150m" class="filter_option">150+ m</option>
                        </select>
                    </div> <!-- .col-md-12 -->
                </div> <!-- .row -->
                <div class="row">
                    <div class="col-md-12">
                        <p>Energielabel</p>
                        <select id="energie" name="energie">
                            <option value="default" disabled="disabled" selected="selected">Selecteer</option>
                            <option value="a-label" class="filter_option">A-label</option>
                            <option value="b-label" class="filter_option">B-label</option>
                            <option value="c-label" class="filter_option">C-label</option>
                            <option value="d-label" class="filter_option">D-label</option>
                            <option value="e-label" class="filter_option">E-label</option>
                            <option value="f-label" class="filter_option">F-label</option>
                            <option value="g-label" class="filter_option">G-label</option>
                        </select>
                    </div> <!-- .col-md-12 -->
                </div> <!-- .row -->
                <div class="row">
                    <div class="col-md-12">
                        <p>Prijsklasse</p>
                        <select id="sale_amount" name="sale_amount">
                            <option value="default" disabled="disabled" selected="selected">Selecteer</option>
                            <option value="0-50000" class="filter_option">€ 0 - 50.000</option>
                            <option value="0-75000" class="filter_option">€ 0 - € 75.000</option>
                            <option value="0-100000" class="filter_option">€ 0 - € 100.000</option>
                            <option value="0-125000" class="filter_option">€ 0 - € 125.000</option>
                            <option value="0-150000" class="filter_option">€ 0 - € 150.000</option>
                            <option value="0-175000" class="filter_option">€ 0 - € 175.000</option>
                            <option value="0-200000" class="filter_option">€ 0 - € 200.000</option>
                            <option value="0-225000" class="filter_option">€ 0 - € 225.000</option>
                            <option value="0-250000" class="filter_option">€ 0 - € 250.000</option>
                            <option value="0-275000" class="filter_option">€ 0 - € 275.000</option>
                            <option value="0-300000" class="filter_option">€ 0 - € 300.000</option>
                            <option value="0-325000" class="filter_option">€ 0 - € 325.000</option>
                            <option value="0-350000" class="filter_option">€ 0 - € 350.000</option>
                            <option value="0-375000" class="filter_option">€ 0 - € 375.000</option>
                            <option value="0-400000" class="filter_option">€ 0 - € 400.000</option>
                            <option value="0-450000" class="filter_option">€ 0 - € 450.000</option>
                            <option value="0-500000" class="filter_option">€ 0 - € 500.000</option>
                            <option value="0-550000" class="filter_option">€ 0 - € 550.000</option>
                            <option value="0-600000" class="filter_option">€ 0 - € 600.000</option>
                            <option value="0-650000" class="filter_option">€ 0 - € 650.000</option>
                            <option value="0-700000" class="filter_option">€ 0 - € 700.000</option>
                            <option value="0-750000" class="filter_option">€ 0 - € 750.000</option>
                            <option value="0-800000" class="filter_option">€ 0 - € 800.000</option>
                            <option value="0-900000" class="filter_option">€ 0 - € 900.000</option>
                            <option value="0-1000000" class="filter_option">€ 0 - € 1.000.000</option>
                            <option value="0-1250000" class="filter_option">€ 0 - € 1.250.000</option>
                            <option value="0-1500000" class="filter_option">€ 0 - € 1.500.000</option>
                            <option value="0-2000000" class="filter_option">€ 0 - € 2.000.000</option>
                        </select>
                    </div> <!-- .col-md-12 -->
                </div> <!-- /.row -->
            </nav>
        </div>
</div>
<div class="container">
    <div class="row row-centered">
        <div class="col-md-4 col-centered">
            <form class="navbar-form" role="search" action="/result">
                <div class="input-group">
                    <input type="text" name="search" class="form-control" placeholder="Zoeken naar ..."/>
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </span>
                </div>
            </form>
        </div>
    </div>
</div>
<?php echo $this->layout()->content ?><br />


<div class="navbar navbar-default">
    <div class="container">
        <div class="navbar-text"><span class="glyphicon glyphicon-copyright-mark"/> 2000-2015 Funda Real Estate B.V.</div>
    </div>
</div>
</body>
</html>