<a id="filter" class="sidebar" href="#sidr" xmlns="http://www.w3.org/1999/html"><p class="vertical-text lead">
        FILTERS</p></a>
<div id="sidr">
    <form action="/result">
        <nav class="menu slide-menu-left">
            <ul>
                <p>Aanwezigheid van</p>
                <input name="balkon" type="checkbox">Balkon<br>
                <input name="lift" type="checkbox">Lift <br>
                <input name="garage" type="checkbox">Garage <br>
                <input name="tuin" type="checkbox">Tuin<br>
                <input name="zwembad" type="checkbox">Zwembad <br>
                <hr/>
                <p>Aantal kamers</p>
                <input name="kamers" value="1+kamers" type="radio">1 kamer<br>
                <input name="kamers" value="2+kamers" type="radio">2+ kamers<br>
                <input name="kamers" value="3+kamers" type="radio">3+ kamers<br>
                <input name="kamers" value="4+kamers" type="radio">4+ kamers<br>
                <hr/>
                <p>Woonoppervlakte</p>
                <select id="woonoppervlakte" name="woonoppervlakte">
                    <option value="default" disabled="disabled" selected="selected">Selecteer</option>
                    <option value="50m" class="filter_option">50+ m</option>
                    <option value="75m" class="filter_option">75+ m</option>
                    <option value="100m" class="filter_option">100+ m</option>
                    <option value="150m" class="filter_option">150+ m</option>
                </select>
                <hr/>
                <p>Energielabel</p>
                <select id="energie" name="energie">
                    <option value="default" disabled="disabled" selected="selected">Selecteer</option>
                    <option value="a-label" class="filter_option">A-label</option>
                    <option value="b-label" class="filter_option">B-label</option>
                    <option value="c-label" class="filter_option">C-label</option>
                    <option value="d-label" class="filter_option">D-label</option>
                    <option value="e-label" class="filter_option">E-label</option>
                    <option value="f-label" class="filter_option">F-label</option>
                    <option value="g-label" class="filter_option">G-label</option>
                </select>
                <hr/>
                <p>Prijs</p>
                <select id="sale_amount" name="sale_amount">
                    <option value="default" disabled="disabled" selected="selected">Selecteer</option>
                    <option value="0-50000" class="filter_option">€ 0 - 50.000</option>
                    <option value="0-75000" class="filter_option">€ 0 - € 75.000</option>
                    <option value="0-100000" class="filter_option">€ 0 - € 100.000</option>
                    <option value="0-125000" class="filter_option">€ 0 - € 125.000</option>
                    <option value="0-150000" class="filter_option">€ 0 - € 150.000</option>
                    <option value="0-175000" class="filter_option">€ 0 - € 175.000</option>
                    <option value="0-200000" class="filter_option">€ 0 - € 200.000</option>
                    <option value="0-225000" class="filter_option">€ 0 - € 225.000</option>
                    <option value="0-250000" class="filter_option">€ 0 - € 250.000</option>
                    <option value="0-275000" class="filter_option">€ 0 - € 275.000</option>
                    <option value="0-300000" class="filter_option">€ 0 - € 300.000</option>
                    <option value="0-325000" class="filter_option">€ 0 - € 325.000</option>
                    <option value="0-350000" class="filter_option">€ 0 - € 350.000</option>
                    <option value="0-375000" class="filter_option">€ 0 - € 375.000</option>
                    <option value="0-400000" class="filter_option">€ 0 - € 400.000</option>
                    <option value="0-450000" class="filter_option">€ 0 - € 450.000</option>
                    <option value="0-500000" class="filter_option">€ 0 - € 500.000</option>
                    <option value="0-550000" class="filter_option">€ 0 - € 550.000</option>
                    <option value="0-600000" class="filter_option">€ 0 - € 600.000</option>
                    <option value="0-650000" class="filter_option">€ 0 - € 650.000</option>
                    <option value="0-700000" class="filter_option">€ 0 - € 700.000</option>
                    <option value="0-750000" class="filter_option">€ 0 - € 750.000</option>
                    <option value="0-800000" class="filter_option">€ 0 - € 800.000</option>
                    <option value="0-900000" class="filter_option">€ 0 - € 900.000</option>
                    <option value="0-1000000" class="filter_option">€ 0 - € 1.000.000</option>
                    <option value="0-1250000" class="filter_option">€ 0 - € 1.250.000</option>
                    <option value="0-1500000" class="filter_option">€ 0 - € 1.500.000</option>
                    <option value="0-2000000" class="filter_option">€ 0 - € 2.000.000</option>
                </select>
                <hr/>
            </ul>
        </nav>
</div>