<!--Sidebar created by: Adriel walter-->
<!--Sidr.phtml (view) created by: Isaac de Cuba-->
<!--Form titles edit by: Serhildan Akdeniz-->
<a id="filter" class="sidebar" href="#sidr" xmlns="http://www.w3.org/1999/html"><h4 class="vertical-text dev-mode">FILTERS</h4></a>
<div id="sidr">
    <form action="/result">
        <nav class="menu slide-menu-left">
            <ul>
                <div class="form-group">
                    <label class="control-label">Aanwezigheid van</label>

                    <div class="checkbox">
                        <label><input type="checkbox" value="balkon">Balkon</label>
                    </div>
                    <div class="checkbox">
                        <label><input type="checkbox" value="lift">Lift</label>
                    </div>
                    <div class="checkbox">
                        <label><input type="checkbox" value="garage">Garage</label>
                    </div>
                    <div class="checkbox">
                        <label><input type="checkbox" value="tuin">Tuin</label>
                    </div>
                    <div class="checkbox">
                        <label><input type="checkbox" value="zwembad">Zwembad</label>
                    </div>
                </div>
                <hr/>
                <div class="form-group">
                    <label class="control-label">Aantal kamers</label>

                    <div class="radio">
                        <label><input type="radio" name="kamers" value="1+kamers">1 kamer</label>
                    </div>
                    <div class="radio">
                        <label><input type="radio" name="kamers" value="2+kamers">2+ kamers</label>
                    </div>
                    <div class="radio">
                        <label><input type="radio" name="kamers" value="3+kamers">3+ kamers</label>
                    </div>
                    <div class="radio">
                        <label><input type="radio" name="kamers" value="4+kamers">4+ kamers</label>
                    </div>
                </div>
                <hr/>
                <div class="form-group">
                    <label for="woonoppervlakte">Woonoppervlakte</label>
                    <select id="woonoppervlakte" name="woonoppervlakte" class="form-control">
                        <option value="default" disabled="disabled" selected="selected">Selecteer</option>
                        <option value="50m" class="filter_option">50+ m</option>
                        <option value="75m" class="filter_option">75+ m</option>
                        <option value="100m" class="filter_option">100+ m</option>
                        <option value="150m" class="filter_option">150+ m</option>
                    </select>
                </div>
                <hr/>
                <div class="form-group">
                    <label for="sale_amount">Prijs</label>
                    <select id="sale_amount" name="sale_amount" class="form-control">
                        <option value="default" disabled="disabled" selected="selected">Selecteer</option>
                        <option value="0-50000" class="filter_option">€ 0 - 50.000</option>
                        <option value="0-75000" class="filter_option">€ 0 - € 75.000</option>
                        <option value="0-100000" class="filter_option">€ 0 - € 100.000</option>
                        <option value="0-125000" class="filter_option">€ 0 - € 125.000</option>
                        <option value="0-150000" class="filter_option">€ 0 - € 150.000</option>
                        <option value="0-175000" class="filter_option">€ 0 - € 175.000</option>
                        <option value="0-200000" class="filter_option">€ 0 - € 200.000</option>
                        <option value="0-225000" class="filter_option">€ 0 - € 225.000</option>
                        <option value="0-250000" class="filter_option">€ 0 - € 250.000</option>
                        <option value="0-275000" class="filter_option">€ 0 - € 275.000</option>
                        <option value="0-300000" class="filter_option">€ 0 - € 300.000</option>
                        <option value="0-325000" class="filter_option">€ 0 - € 325.000</option>
                        <option value="0-350000" class="filter_option">€ 0 - € 350.000</option>
                        <option value="0-375000" class="filter_option">€ 0 - € 375.000</option>
                        <option value="0-400000" class="filter_option">€ 0 - € 400.000</option>
                        <option value="0-450000" class="filter_option">€ 0 - € 450.000</option>
                        <option value="0-500000" class="filter_option">€ 0 - € 500.000</option>
                        <option value="0-550000" class="filter_option">€ 0 - € 550.000</option>
                        <option value="0-600000" class="filter_option">€ 0 - € 600.000</option>
                        <option value="0-650000" class="filter_option">€ 0 - € 650.000</option>
                        <option value="0-700000" class="filter_option">€ 0 - € 700.000</option>
                        <option value="0-750000" class="filter_option">€ 0 - € 750.000</option>
                        <option value="0-800000" class="filter_option">€ 0 - € 800.000</option>
                        <option value="0-900000" class="filter_option">€ 0 - € 900.000</option>
                        <option value="0-1000000" class="filter_option">€ 0 - € 1.000.000</option>
                        <option value="0-1250000" class="filter_option">€ 0 - € 1.250.000</option>
                        <option value="0-1500000" class="filter_option">€ 0 - € 1.500.000</option>
                        <option value="0-2000000" class="filter_option">€ 0 - € 2.000.000</option>
                    </select>
                </div>
            </ul>
        </nav>
</div>