<!--Sidebar created by: Adriel walter-->
<!--Sidr.phtml (view & logic) created by: Isaac de Cuba-->
<!--Form titles edit by: Serhildan Akdeniz-->
<?php
$params = Zend_Controller_Front::getInstance()->getRequest()->getParams();
?>
<a id="filter" class="sidebar" href="#sidr" xmlns="http://www.w3.org/1999/html"><h4 class="vertical-text dev-mode">
        FILTERS</h4></a>
<div id="sidr">
    <form id="sideform" action="/result">
        <nav class="menu slide-menu-left">
            <ul>
                <div class="form-group">
                    <label class="control-label">Aanwezigheid van</label>

                    <div class="checkbox">
                        <label><input type="checkbox" name="aanwezigheid1" value="balkon-dakterras"
                                      onclick="subm()" <?php echo in_array('balkon-dakterras', $params) ? 'checked' : '' ?>>Balkon-Dakterras</label>
                    </div>
                    <div class="checkbox">
                        <label><input type="checkbox" name="aanwezigheid2" value="lift"
                                      onclick="subm()" <?php echo in_array('lift', $params) ? 'checked' : '' ?>>Lift</label>
                    </div>
                    <div class="checkbox">
                        <label><input type="checkbox" name="aanwezigheid3" value="garage"
                                      onclick="subm()" <?php echo in_array('garage', $params) ? 'checked' : '' ?>>Garage</label>
                    </div>
                    <div class="checkbox">
                        <label><input type="checkbox" name="aanwezigheid4" value="tuin"
                                      onclick="subm()" <?php echo in_array('tuin', $params) ? 'checked' : '' ?>>Tuin</label>
                    </div>
                    <div class="checkbox">
                        <label><input type="checkbox" name="aanwezigheid5" value="zwembad"
                                      onclick="subm()" <?php echo in_array('zwembad', $params) ? 'checked' : '' ?>>Zwembad</label>
                    </div>
                </div>
                <hr/>
                <div class="form-group">
                    <label class="control-label">Aantal kamers</label>

                    <div class="radio">
                        <label><input type="radio" name="kamers" value="1+kamers"
                                      onclick="subm()" <?php echo in_array('1+kamers', $params) ? 'checked' : '' ?>>1
                            kamer</label>
                    </div>
                    <div class="radio">
                        <label><input type="radio" name="kamers" value="2+kamers"
                                      onclick="subm()" <?php echo in_array('2+kamers', $params) ? 'checked' : '' ?>>2+
                            kamers</label>
                    </div>
                    <div class="radio">
                        <label><input type="radio" name="kamers" value="3+kamers"
                                      onclick="subm()" <?php echo in_array('3+kamers', $params) ? 'checked' : '' ?>>3+
                            kamers</label>
                    </div>
                    <div class="radio">
                        <label><input type="radio" name="kamers" value="4+kamers"
                                      onclick="subm()" <?php echo in_array('4+kamers', $params) ? 'checked' : '' ?>>4+
                            kamers</label>
                    </div>
                </div>
                <hr/>
                <div class="form-group">
                    <label for="woonoppervlakte">Woonoppervlakte</label>
                    <select id="woonoppervlakte" name="woonoppervlakte" class="form-control">
                        <option
                            value="default" <?php echo array_key_exists('woonoppervlakte', $params) ? '' : 'disabled="disabled" selected="selected"' ?>>
                            Selecteer
                        </option>
                        <option value="0-50-woonopp" class="filter_option"
                                onclick="subm()" <?php echo in_array('0-50-woonopp', $params) ? 'selected' : '' ?>>0-50
                            m<sup>2</sup></option>
                        <option value="50+woonopp" class="filter_option"
                                onclick="subm()" <?php echo in_array('50+woonopp', $params) ? 'selected' : '' ?>>50+
                            m<sup>2</sup></option>
                        <option value="75+woonopp" class="filter_option"
                                onclick="subm()" <?php echo in_array('75+woonopp', $params) ? 'selected' : '' ?>>75+
                            m<sup>2</sup></option>
                        <option value="100+woonopp" class="filter_option"
                                onclick="subm()" <?php echo in_array('100+woonopp', $params) ? 'selected' : '' ?>>100+ m<sup>2</sup>
                        </option>
                    </select>
                </div>
                <hr/>
                <div class="form-group">
                    <label for="sale_amount">Prijs</label>
                    <select id="sale_amount" name="sale_amount" class="form-control">
                        <option
                            value="default" <?php echo array_key_exists('sale_amount', $params) ? '' : 'disabled="disabled" selected="selected"' ?>>
                            Selecteer
                        </option>
                        <option value="0-50000" class="filter_option"
                                onclick="subm()" <?php echo in_array('0-50000', $params) ? 'selected' : '' ?>>€ 0 -
                            50.000
                        </option>
                        <option value="0-75000" class="filter_option"
                                onclick="subm()" <?php echo in_array('0-75000', $params) ? 'selected' : '' ?>>€ 0 - €
                            75.000
                        </option>
                        <option value="0-100000" class="filter_option"
                                onclick="subm()" <?php echo in_array('0-100000', $params) ? 'selected' : '' ?>>€ 0 - €
                            100.000
                        </option>
                        <option value="0-125000" class="filter_option"
                                onclick="subm()" <?php echo in_array('0-125000', $params) ? 'selected' : '' ?>>€ 0 - €
                            125.000
                        </option>
                        <option value="0-150000" class="filter_option"
                                onclick="subm()" <?php echo in_array('0-150000', $params) ? 'selected' : '' ?>>€ 0 - €
                            150.000
                        </option>
                        <option value="0-175000" class="filter_option"
                                onclick="subm()" <?php echo in_array('0-175000', $params) ? 'selected' : '' ?>>€ 0 - €
                            175.000
                        </option>
                        <option value="0-200000" class="filter_option"
                                onclick="subm()" <?php echo in_array('0-200000', $params) ? 'selected' : '' ?>>€ 0 - €
                            200.000
                        </option>
                        <option value="0-225000" class="filter_option"
                                onclick="subm()" <?php echo in_array('0-225000', $params) ? 'selected' : '' ?>>€ 0 - €
                            225.000
                        </option>
                        <option value="0-250000" class="filter_option"
                                onclick="subm()" <?php echo in_array('0-250000', $params) ? 'selected' : '' ?>>€ 0 - €
                            250.000
                        </option>
                        <option value="0-275000" class="filter_option"
                                onclick="subm()" <?php echo in_array('0-275000', $params) ? 'selected' : '' ?>>€ 0 - €
                            275.000
                        </option>
                        <option value="0-300000" class="filter_option"
                                onclick="subm()" <?php echo in_array('0-300000', $params) ? 'selected' : '' ?>>€ 0 - €
                            300.000
                        </option>
                        <option value="0-325000" class="filter_option"
                                onclick="subm()" <?php echo in_array('0-325000', $params) ? 'selected' : '' ?>>€ 0 - €
                            325.000
                        </option>
                        <option value="0-350000" class="filter_option"
                                onclick="subm()" <?php echo in_array('0-350000', $params) ? 'selected' : '' ?>>€ 0 - €
                            350.000
                        </option>
                        <option value="0-375000" class="filter_option"
                                onclick="subm()" <?php echo in_array('0-375000', $params) ? 'selected' : '' ?>>€ 0 - €
                            375.000
                        </option>
                        <option value="0-400000" class="filter_option"
                                onclick="subm()" <?php echo in_array('0-400000', $params) ? 'selected' : '' ?>>€ 0 - €
                            400.000
                        </option>
                        <option value="0-450000" class="filter_option"
                                onclick="subm()" <?php echo in_array('0-450000', $params) ? 'selected' : '' ?>>€ 0 - €
                            450.000
                        </option>
                        <option value="0-500000" class="filter_option"
                                onclick="subm()" <?php echo in_array('0-500000', $params) ? 'selected' : '' ?>>€ 0 - €
                            500.000
                        </option>
                        <option value="0-550000" class="filter_option"
                                onclick="subm()" <?php echo in_array('0-550000', $params) ? 'selected' : '' ?>>€ 0 - €
                            550.000
                        </option>
                        <option value="0-600000" class="filter_option"
                                onclick="subm()" <?php echo in_array('0-600000', $params) ? 'selected' : '' ?>>€ 0 - €
                            600.000
                        </option>
                        <option value="0-650000" class="filter_option"
                                onclick="subm()" <?php echo in_array('0-650000', $params) ? 'selected' : '' ?>>€ 0 - €
                            650.000
                        </option>
                        <option value="0-700000" class="filter_option"
                                onclick="subm()" <?php echo in_array('0-700000', $params) ? 'selected' : '' ?>>€ 0 - €
                            700.000
                        </option>
                        <option value="0-750000" class="filter_option"
                                onclick="subm()" <?php echo in_array('0-750000', $params) ? 'selected' : '' ?>>€ 0 - €
                            750.000
                        </option>
                        <option value="0-800000" class="filter_option"
                                onclick="subm()" <?php echo in_array('0-800000', $params) ? 'selected' : '' ?>>€ 0 - €
                            800.000
                        </option>
                        <option value="0-900000" class="filter_option"
                                onclick="subm()" <?php echo in_array('0-900000', $params) ? 'selected' : '' ?>>€ 0 - €
                            900.000
                        </option>
                        <option value="0-1000000" class="filter_option"
                                onclick="subm()" <?php echo in_array('0-1000000', $params) ? 'selected' : '' ?>>€ 0 - €
                            1.000.000
                        </option>
                        <option value="0-1500000" class="filter_option"
                                onclick="subm()" <?php echo in_array('0-1500000', $params) ? 'selected' : '' ?>>€ 0 - €
                            1.250.000
                        </option>
                        <option value="0-2000000" class="filter_option"
                                onclick="subm()" <?php echo in_array('0-2000000', $params) ? 'selected' : '' ?>>€ 0 - €
                            1.500.000
                        </option>
                        <option value="0-6000000" class="filter_option"
                                onclick="subm()" <?php echo in_array('0-6000000', $params) ? 'selected' : '' ?>>€ 0 - €
                            2.000.000
                        </option>
                    </select>
                </div>
            </ul>
        </nav>
</div>
<script>
    function subm() {
        document.getElementById('sideform').submit();
    }
</script>