<div class="container">
    <div class="row">
        <div class="col-md-12">
            <?php
            /**
             * author isaac
             * NIET VERWIJDEREN!!
             */

            $time_start = microtime(true);

            ?>
            <p>
                <?php

                $params['filters']['city'] = $this->search; ?>
                <?php echo $this->fundaApiConnector->buildUrl($params); ?>
            </p>

            <p>
                Searched for: <?php echo $params['filters']['city']; ?>
            </p>

            <p>
                utrecht:
                <?php echo $this->fundaApiConnector->totalObjects($params); ?>
            <ul class="list-group">
                <?php foreach ($this->fundaApiConnector->getCollection($params) as $house): ?>
                <li class="list-group-item">
                    <?php echo sprintf('Adres: %s', $house->Adres) . "<br>"; ?>
                    <?php echo sprintf('Lat: %s', $house->WGS84_Y) . "<br>"; ?>
                    <?php echo sprintf('Lng: %s', $house->WGS84_X) . "<br>"; ?>
                </li>
                <?php endforeach; ?>
            </ul>
            </p>

            <p>
                rotterdam:
                <?php echo $this->fundaApiConnector->totalObjectsCity($params, 'rotterdam'); ?>
            </p>

            <p>
                den haag:
                <?php echo $this->fundaApiConnector->totalObjectsCity($params, 'den-haag'); ?>
            </p>

            <p>
                dordrecht:
                <?php echo $this->fundaApiConnector->totalObjectsCity($params, 'dordrecht'); ?>
            </p>

            <p>
                schiedam:
                <?php echo $this->fundaApiConnector->totalObjectsCity($params, 'schiedam'); ?>
            </p>
            <?php
            $time_end = microtime(true);
            //dividing with 60 will give the execution time in minutes other wise seconds
            $execution_time = ($time_end - $time_start) / 60;

            //execution time of the script
            echo '<b>Total Execution Time:</b> ' . $execution_time . ' Mins';
            ?>
            <h2>ss</h2>
        </div>
    </div>
</div>

fe49cdab-e35d-4e28-81b6-907bc63dc02d
fe49cdab-e35d-4e28-81b6-907bc63dc02d